import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider, auth } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModalProvider } from "@/components/modal-provider";
import getUserPlaylists from "@/actions/get-user-playlists";
import { PlayerContextProvider } from "@/contexts/player-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();
  const playlists = await getUserPlaylists(userId);

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            forcedTheme="dark"
          >
            <ModalProvider playlists={playlists} />
            <Toaster />
            <PlayerContextProvider>{children}</PlayerContextProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
