import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider, auth } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { dark } from "@clerk/themes";

import "./globals.css";
import getUserPlaylists from "@/actions/get-user-playlists";
import { ThemeProvider } from "@/components/theme-provider";
import { ModalProvider } from "@/components/modal-provider";
import { PlayerContextProvider } from "@/contexts/player-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();
  const playlists = await getUserPlaylists(userId);

  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: "#a3e635",
          colorTextOnPrimaryBackground: "#0a0a0a",
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            forcedTheme="dark"
          >
            <ModalProvider playlists={playlists} />
            <Toaster />
            <PlayerContextProvider>{children}</PlayerContextProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
